### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by hi-204** [0niel/neural-network-aimbot#1]
I have built the program but when I run the exe I get the error: C:\Users\*****\neural-network-aimbot\x64\Release>ez-neural-network-aim.exe
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.5.3) Error: Parsing error (Failed to parse NetParameter file: C:\Users\*****\neural-network-aimbot\x64\Release\yolov3-tiny.cfg) in cv::dnn::dnn4_v20210608::readNetFromDarknet, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\darknet\darknet_importer.cpp, line 207. Can anyone help?

P.S. I'm new to visual studios so its possible that I may have compiled it wrong.

**Comment by 0niel** [comment]
yolov3-tiny.cfg should be located in the output folder an exe file https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-tiny.cfg

**Comment by hi-204** [comment]
Ok. Does that mean I have to download it? As I said I’m quite new to visual studios.

**Comment by 0niel** [comment]
Yes. The config is needed both for training the model and for using it

**Comment by hi-204** [comment]
Ok, thanks! Once downloaded I should put it in the folder with the exe? I tried this and it didn't work.

**Comment by hi-204** [comment]
Never mind I got it to work. Thank you for your time and effort!

**Comment by hi-204** [comment]
I might just not understand how yolo works but I just tried it and it works quite well however I can't get to recognize objects or lock on to them. I'm using the yolo.cfg and yolo.weights from another neural network I had but it won't work.

**Comment by 0niel** [comment]
https://youtu.be/zJDUhGL26iU

**Comment by hi-204** [comment]
Thanks! I really appreciate the help. I'll train it when I'm free and let you know how it goes.

**Comment by jkjkjk254** [comment]
> I have built the program but when I run the exe I get the error: C:\Users*****\neural-network-aimbot\x64\Release>ez-neural-network-aim.exe OpenCV: terminate handler is called! The last OpenCV error is: OpenCV(4.5.3) Error: Parsing error (Failed to parse NetParameter file: C:\Users*****\neural-network-aimbot\x64\Release\yolov3-tiny.cfg) in cv::dnn::dnn4_v20210608::readNetFromDarknet, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\darknet\darknet_importer.cpp, line 207. Can anyone help?
> 
> P.S. I'm new to visual studios so its possible that I may have compiled it wrong.



> Never mind I got it to work. Thank you for your time and effort!

**Comment by jkjkjk254** [comment]
> Never mind I got it to work. Thank you for your time and effort!

Could you please tell me how you got it to work. Thanks in advance!

**Comment by hi-204** [comment]
I put the .weights folder and .cfg in with the exe. I’m having some trouble

**Comment by hi-204** [comment]
With the training.

**Comment by hi-204** [comment]
Sorry my phone pc turned off as I was typing

**Comment by hi-204** [comment]
Just phone lol. I guess I can’t think today.

**Comment by 0niel** [comment]
> I put the .weights folder and .cfg in with the exe. I’m having some trouble

What are your problems?
