### ISSUE TITLE
Проблема с opencv

### ISSUE THREAD

**Issue by lOkmil** [0niel/neural-network-aimbot#3]
Скачал,прописал везде OpenCv,скомплировал программу но выдает ошибку что нет d.dll (файл пробовал копировать из папки OpenCv)
![image](https://user-images.githubusercontent.com/87613327/127014179-e469bff2-900f-4b9e-a762-d984b26efc0f.png)

**Comment by 0niel** [comment]
Положи данную библиотеку рядом с выходным .exe файлом в папке релизов.

**Comment by lOkmil** [comment]
> Положи данную библиотеку рядом с выходным .exe файлом в папке релизов.

![image](https://user-images.githubusercontent.com/87613327/127034555-167301fa-3ec4-4200-85b2-d97aedfa3c68.png)
Новая ошибка

**Comment by lOkmil** [comment]
> Положи данную библиотеку рядом с выходным .exe файлом в папке релизов.

Все,спасибо,исправил.
