### ISSUE TITLE
I cant open

### ISSUE THREAD

**Issue by jkjkjk254** [0niel/neural-network-aimbot#4]
i get this error could someone help me, ive tried to add the cfg file but it still doesnt work
 called! The last OpenCV error is:
OpenCV(4.5.3) Error: Parsing error (Failed to parse NetParameter file: C:\Users\vin\Desktop\neural-network-aimbot-main\x64\Release\yolov3-tiny.weights) in cv::dnn::dnn4_v20210608::readNetFromDarknet, file C:\build\master_winpack-build-win64-vc15\opencv\modules\dnn\src\darknet\darknet_importer.cpp, line 214

**Comment by jkjkjk254** [comment]
maybe i compiled wrong

**Comment by 0niel** [comment]
Hello. https://github.com/0niel/neural-network-aimbot/issues/1#issuecomment-886069035

**Comment by jkjkjk254** [comment]
another issue came up, its that the program start but it gets stuck on )penCV(ocl4dnn): consider to specify kernel configuration cache directory via OPENCV_OCL4DNN_CONFIG_PATH parameter. and the smaller window doesnt come up

**Comment by jkjkjk254** [comment]
could you please help me when you are free, yea solved the first one

**Comment by 0niel** [comment]
Try to comment 115-118 lines in detector.cpp. This will start the detector in non-OCL mode. https://github.com/0niel/neural-network-aimbot/blob/211d5c30c15af416135bdb0b0f315f992a02ebf2/ez-neural-network-aim/detector.cpp#L115-L118
