### ISSUE TITLE
Failed to open NetParameter file: yolov3-tiny.cfg

### ISSUE THREAD

**Issue by vervoortkobe** [0niel/neural-network-aimbot#6]
As I'm running the code from the repo, I get the following error:
```
OpenCV(4.6.0) Error: Parsing error (Failed to open NetParameter file: D:\Downloads\neural-network-aimbot-main\neural- 
network-aimbot-main\x64\Debug\yolov3-tiny.cfg) in cv::dnn::dnn4_v20220524::readNetFromDarknet, file  
C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\darknet\darknet_importer.cpp, line 210
```
So I thought it would be solved if I would create the yolov3-tiny.cfg file myself and paste it in the destinated directory.
But I'm still getting this error...

How can I solve it? What am I doing wrong?

**Comment by MoscowMoscovv** [comment]
did you solved it?

**Comment by vervoortkobe** [comment]
In the meantime, I gave up on this project. I kind of got it to work though, but it didn't work as well as I expected it would.
It's already a long time ago, since i opened this issue, also.

But I believe I got it to work by just downloading the yolov3-tiny.cfg file from somewhere on github.
You could try this one out: https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-tiny.cfg

Good luck!
